// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(UkTransportDbContext))]
    [Migration("20260801111810_Initial5")]
    partial class Initial5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.BusCallingPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BusStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusTimetableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScheduledDayOffset")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusStopId");

                    b.HasIndex("BusTimetableId");

                    b.ToTable("BusCallingPoints");
                });

            modelBuilder.Entity("Backend.Models.BusDataset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BusDatasets");
                });

            modelBuilder.Entity("Backend.Models.BusHoliday", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BusTimetableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOperating")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicHolidayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusTimetableId");

                    b.HasIndex("PublicHolidayName");

                    b.ToTable("BusHolidays");
                });

            modelBuilder.Entity("Backend.Models.BusSpecialDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BusTimetableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsOperating")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BusTimetableId");

                    b.ToTable("BusSpecialDays");
                });

            modelBuilder.Entity("Backend.Models.BusTimetable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("DestinationBusStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginBusStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<int>("ScheduledDayOffset")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<string>("TripJourneyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.Property<int>("WeeksOfMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.HasIndex("DepartureTime");

                    b.HasIndex("DestinationBusStopId");

                    b.HasIndex("LineName");

                    b.HasIndex("OperatorId");

                    b.HasIndex("OriginBusStopId");

                    b.HasIndex("TripJourneyKey");

                    b.ToTable("BusTimetables");
                });

            modelBuilder.Entity("Backend.Models.PublicHoliday", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("Backend.Models.BusCallingPoint", b =>
                {
                    b.HasOne("Backend.Models.BusTimetable", "BusTimetable")
                        .WithMany("BusCallingPoints")
                        .HasForeignKey("BusTimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTimetable");
                });

            modelBuilder.Entity("Backend.Models.BusHoliday", b =>
                {
                    b.HasOne("Backend.Models.BusTimetable", "BusTimetable")
                        .WithMany("BusHolidays")
                        .HasForeignKey("BusTimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.PublicHoliday", "PublicHoliday")
                        .WithMany()
                        .HasForeignKey("PublicHolidayName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTimetable");

                    b.Navigation("PublicHoliday");
                });

            modelBuilder.Entity("Backend.Models.BusSpecialDay", b =>
                {
                    b.HasOne("Backend.Models.BusTimetable", "BusTimetable")
                        .WithMany("BusSpecialDays")
                        .HasForeignKey("BusTimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTimetable");
                });

            modelBuilder.Entity("Backend.Models.BusTimetable", b =>
                {
                    b.HasOne("Backend.Models.BusDataset", "BusDataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusDataset");
                });

            modelBuilder.Entity("Backend.Models.BusTimetable", b =>
                {
                    b.Navigation("BusCallingPoints");

                    b.Navigation("BusHolidays");

                    b.Navigation("BusSpecialDays");
                });
#pragma warning restore 612, 618
        }
    }
}
