// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(UkTransportDbContext))]
    [Migration("20260725185934_Initial1")]
    partial class Initial1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.BusCallingPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ArrivalDayOffset")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("BusStopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusTimetableId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DepartureDayOffset")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusStopId");

                    b.HasIndex("BusTimetableId");

                    b.ToTable("BusCallingPoints");
                });

            modelBuilder.Entity("Backend.Models.BusTimetable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ArrivalDayOffset")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatorRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginDepartureKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RunsOnBankHolidays")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ValidTo")
                        .HasColumnType("date");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LineName");

                    b.HasIndex("OperatorRef");

                    b.HasIndex("OriginDepartureKey");

                    b.ToTable("BusTimetables");
                });

            modelBuilder.Entity("Backend.Models.BusCallingPoint", b =>
                {
                    b.HasOne("Backend.Models.BusTimetable", "BusTimetable")
                        .WithMany("BusCallingPoints")
                        .HasForeignKey("BusTimetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTimetable");
                });

            modelBuilder.Entity("Backend.Models.BusTimetable", b =>
                {
                    b.Navigation("BusCallingPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
